const REEL_REPLIES = [
  "bruh im literally deceased 💀",
  "STOPPP this is too much 😭",
  "no way 💀💀💀",
  "im crying real tears rn",
  "this is unhinged and i love it",
  "whoever made this needs a raise",
  "im sending this to everyone i know",
  "bro woke up and chose violence 💀",
  "this lives in my head rent free now",
  "i just spit out my water",
  "the accuracy is PAINFUL",
  "why is this so real tho 😭",
  "i feel personally attacked",
  "this has no business being this funny",
  "im not okay after watching this",
  "LMAOOO bruh",
  "this is peak content right here",
  "i replayed this like 47 times",
  "how do i unsee this",
  "the way i SCREAMED",
  "nah this is crazy 😭😭",
  "whoever relates to this needs therapy (its me)",
  "this ruined my whole day (in a good way)",
  "im showing this to my therapist",
  "bestie why would you send me this at this hour 💀",
  "the fact that this exists is sending me",
  "i cant breathe 😭",
  "this is the funniest thing ive seen all week",
  "bruh the ending caught me off guard",
  "im literally on the floor rn",
  "why did this hit so different",
  "the way i just ugly laughed",
  "this unlocked a memory i didnt want",
  "tag me in the comments im fighting someone",
  "this should be illegal 😭",
  "i need the full version of this",
  "bro really said copy paste 💀",
  "im stealing this for my story ngl",
  "the accuracy tho 📈",
  "this is so niche yet so relatable",
  "im adding this to my saved",
  "did we just become best friends bc of this reel",
  "okay but why is no one talking about this",
  "this awakened something in me",
  "not me watching this on repeat at 3am",
  "the audacity of this reel 💀",
  "this deserves an oscar",
  "okay slay i guess",
  "real ones understand this",
  "this is criminally underrated",
  "bro just ended everyones career with this",
  "nahhh who approved this 😭😭",
  "im making this my whole personality now",
  "this is so chaotic i love it",
  "the way this is literally me",
  "im in tears and not the good kind",
  "this reel owns me now",
  "okay that transition was smooth tho",
  "bruh moment of the century",
  "this goes unreasonably hard",
  "im telling my kids about this reel"
];
