version: '3.8'
services:
  webserver:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
      - ./backend:/var/www/backend
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: office_tracker
      MYSQL_USER: office_user
      MYSQL_PASSWORD: office_pass
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: